//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputSystem/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""BattleScene"",
            ""id"": ""4b094081-f848-45bf-bd00-c11d36a28e58"",
            ""actions"": [
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""8a574952-27c0-4ee0-8839-e6eb120ff4a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""ce62a096-8f78-4e63-93a9-029d6938f5c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""f9c40c09-5028-4ec8-aaac-ccb971d953eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""1b35d70d-1718-4b8c-87e3-d8d656b164b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slow"",
                    ""type"": ""Button"",
                    ""id"": ""d4fb6ed4-06b9-4e58-b9f5-b3d1937f90fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6612e265-2bf6-4b74-b679-0c5c6b66d0c5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e78c967d-9102-4f84-9470-54a90295ce7f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8153804-7a0d-4e3d-b6c7-7ef8aff0d175"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ffd0694-9c9f-448f-8704-74fce16fcd59"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d667acfc-6d63-4ec4-9294-1d6f58882538"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BattleScene
        m_BattleScene = asset.FindActionMap("BattleScene", throwIfNotFound: true);
        m_BattleScene_Down = m_BattleScene.FindAction("Down", throwIfNotFound: true);
        m_BattleScene_Up = m_BattleScene.FindAction("Up", throwIfNotFound: true);
        m_BattleScene_Left = m_BattleScene.FindAction("Left", throwIfNotFound: true);
        m_BattleScene_Right = m_BattleScene.FindAction("Right", throwIfNotFound: true);
        m_BattleScene_Slow = m_BattleScene.FindAction("Slow", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattleScene
    private readonly InputActionMap m_BattleScene;
    private List<IBattleSceneActions> m_BattleSceneActionsCallbackInterfaces = new List<IBattleSceneActions>();
    private readonly InputAction m_BattleScene_Down;
    private readonly InputAction m_BattleScene_Up;
    private readonly InputAction m_BattleScene_Left;
    private readonly InputAction m_BattleScene_Right;
    private readonly InputAction m_BattleScene_Slow;
    public struct BattleSceneActions
    {
        private @GameInputs m_Wrapper;
        public BattleSceneActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Down => m_Wrapper.m_BattleScene_Down;
        public InputAction @Up => m_Wrapper.m_BattleScene_Up;
        public InputAction @Left => m_Wrapper.m_BattleScene_Left;
        public InputAction @Right => m_Wrapper.m_BattleScene_Right;
        public InputAction @Slow => m_Wrapper.m_BattleScene_Slow;
        public InputActionMap Get() { return m_Wrapper.m_BattleScene; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattleSceneActions set) { return set.Get(); }
        public void AddCallbacks(IBattleSceneActions instance)
        {
            if (instance == null || m_Wrapper.m_BattleSceneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BattleSceneActionsCallbackInterfaces.Add(instance);
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Slow.started += instance.OnSlow;
            @Slow.performed += instance.OnSlow;
            @Slow.canceled += instance.OnSlow;
        }

        private void UnregisterCallbacks(IBattleSceneActions instance)
        {
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Slow.started -= instance.OnSlow;
            @Slow.performed -= instance.OnSlow;
            @Slow.canceled -= instance.OnSlow;
        }

        public void RemoveCallbacks(IBattleSceneActions instance)
        {
            if (m_Wrapper.m_BattleSceneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBattleSceneActions instance)
        {
            foreach (var item in m_Wrapper.m_BattleSceneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BattleSceneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BattleSceneActions @BattleScene => new BattleSceneActions(this);
    public interface IBattleSceneActions
    {
        void OnDown(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnSlow(InputAction.CallbackContext context);
    }
}
